name: Docker Image CI

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development
    - features/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true

    - name: Build the Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        tags: jibarra/https-server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
